# overlays/dev/kustomization.yml
resources:
- ../../base

namespace: api

namePrefix: dev-

commonLabels:
  env: dev

patches:
- path: patchDeployment.yaml
- path: patchIngress.yaml
- path: patchService.yaml