# overlays/dev/kustomization.yml
resources:
- ../../base

namespace: api

namePrefix: dev-

commonLabels:
  env: dev

patches:
- path: patchDeployment.yml
- path: patchIngress.yml
- path: patchService.yml