spec:
  rules:
    - host: host.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-server  # ✅ 존재하는 서비스 참조
                port:
                  number: 8080  # ✅ 실제 `api-server`의 포트 (8080)
